[project]
name = "sequential-thinking-mcp-v2"
version = "0.1.0"
description = "Unified Sequential Thinking MCP with Memory Bank integration"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    # "pkg-resources>=0.0.0",
]
